version: "3"
services:
    web:
        depends_on:
            - redis
        build: .
        ports:
            - "3000:3000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        links:
            - "redis"
    redis:
        image: docker.io/redis
        volumes:
          - .redisDB/:/data

