---
- name: Install required packages
  yum:
    name:
      - "@Development tools"
      - curl
      - policycoreutils-python
      - openssh-server
      - git
      - epel-release
      - redis
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - http
    - https

- name: Enable and start Redis
  service:
    name: redis
    state: started
    enabled: yes

- name: Download nodejs setup
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /home/vagrant/.ansible/tmp

- name: Build source and add repo
  shell: bash /home/vagrant/.ansible/tmp/setup_14.x
  become: yes

- name: Install Nodejs14
  yum:
    name: nodejs

- name: Clone our private repo
  git:
    repo: git@github.com:fbraza/devops-project-dsti-fall-2020.git    
    dest: /home/vagrant/private-repo
    accept_hostkey: yes
  become: no


- name: Install packages for app
  shell: npm install
  args:
    chdir: /home/vagrant/private-repo
